version: '3.8'
services:
  whatsapp_service:
    build: ./whatsapp_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - llm_service

  llm_service:
    build: ./llm_service
    ports:
      - "8001:8001"
    env_file:
      - .env
